/*
 * events.h
 *
 *  Created on: Mar 30, 2023
 *      Author: admin
 */

#ifndef INC_EVENTS_H_
#define INC_EVENTS_H_

enum {

	 SEAGLIDER_EVNT_START_RCVD=600,
	 SEAGLIDER_EVNT_STOP_RCVD,
	 SEAGLIDER_EVNT_TEST_RCVD,
	 SEAGLIDER_EVNT_SEND_TXT_FILE_RCVD,
	 SEAGLIDER_EVNT_CLOCK_RCVD,
	 SEAGLIDER_EVNT_WAKEUP_RCVD,
	 SEAGLIDER_EVNT_DEPTH_RCVD,
	 SEAGLIDER_EVNT_CLEAR_RCVD,
	 SEAGLIDER_EVNT_POFF_RCVD,
	 SEAGLIDER_EVNT_ERRORS_RCVD,
	 HYDROC_EVNT_ERR_BATTERY,
	 HYDROC_EVNT_ERR_TOKEN,
	 HYDROC_EVNT_ERR_ARGUMENT,
	 HYDROC_EVNT_ERR_CHECKSUM,
	 HYDROC_EVNT_ERR_BUFFER,
	 HYDROC_EVNT_ERR_LENGTH,
	 HYDROC_EVNT_ERR_CONFIG,
	 HYDROC_EVNT_ERR_REQUEST,
	 HYDROC_EVNT_ERR_EXT_PUMP,
	 HYDROC_EVNT_INVENTORY_UPDATED,
	 HYDROC_EVNT_CFG_ENTERED,
	 HYDROC_EVNT_CFG_EXITED,
	 HYDROC_EVNT_PUMP_ENABLED,
	 HYDROC_EVNT_PUMP_DISABLED,
     HYDROC_EVNT_BOOTED,
     HYDROC_EVNT_CODS4,
	 HYDROC_EVNT_COTS1
};

enum fsm_states{
	FSM_CHANGE_STATE_TO_S0=200,
	FSM_CHANGE_STATE_TO_S1,
	FSM_CHANGE_STATE_TO_S2,
	FSM_CHANGE_STATE_TO_S3,
	FSM_CHANGE_STATE_TO_S4,
	FSM_CHANGE_STATE_TO_S5,
	FSM_CHANGE_STATE_TO_S6,
	FSM_CHANGE_STATE_TO_S7
};

enum fsm_events{
	FSM_EVNT_SETTINGS_LOADED=300,
	FSM_EVNT_DEFAULT_SETTINGS_LOADED,
	FSM_EVNT_SENSOR_INITIALIZED,
	FSM_EVNT_SENSOR_INIT_ERROR,
	FSM_EVNT_CLOCK_UPDATED,
	FSM_EVNT_ERRORS_SENT,
	FSM_EVNT_DATA_SENT,
	FSM_EVNT_DATA_CANT_BE_SENT,
	FSM_EVNT_DS4_DATA_READY,
	FSM_EVNT_TS1_DATA_READY,
	FSM_EVNT_DS4_PROCESSED,
	FSM_EVNT_TS1_PROCESSED,
	FSM_EVNT_FILES_CREATED,
	FSM_EVNT_FILES_OPENED,
	FSM_EVNT_FILES_CLOSED,
	FSM_EVNT_POST_CONF_FINISHED,
	FSM_EVNT_PRE_CONF_FINISHED,
	FSM_EVNT_FILE_OPEN_ERR,
	FSM_EVNT_DBG1,
	FSM_EVNT_DBG2

};


#endif /* INC_EVENTS_H_ */
