/*
 * events.h
 *
 *  Created on: Mar 30, 2023
 *      Author: admin
 */

#ifndef INC_EVENTS_H_
#define INC_EVENTS_H_

enum {
	UVP6_EVNT_BOOTED=100,
	UVP6_EVNT_LPM_DATA_RCVD,
	UVP6_EVNT_BLK_DATA_RCVD,
	UVP6_EVNT_ACQ_CONF_RCVD,
	UVP6_EVNT_START_ACK_RCVD,
	UVP6_EVNT_START_ERR_RCVD,
	UVP6_EVNT_STOP_ACK_RCVD,
	UVP6_EVNT_ERR_NO_RESPONSE,
	UVP6_EVNT_ERR_BUSY,
	UVP6_EVNT_STARTED_LOW_PROFILE,
	UVP6_EVNT_STARTED_HIGH_PROFILE,
	UVP6_EVNT_POWERED_OFF,
	UVP6_EVNT_POWERED_ON,
	UVP6_EVNT_LPM_DATA_BLOC_END_REACHED,
	UVP6_EVNT_LPM_AGG_DATA_READY,
	UVP6_EVNT_LPM_BUFFER_CLEARED,
	UVP6_EVNT_LPM_AGG_NOTHING_TO_SEND,
	UVP6_EVNT_DEPTH_LH_REACHED_FROM_TOP,
	UVP6_EVNT_DEPTH_LH_REACHED_FROM_BOTTOM,
	SLOCUM_EVNT_GPS_LAT_RCVD,
	SLOCUM_EVNT_GPS_LON_RCVD,
	SLOCUM_EVNT_DIVE_TARGET_DEPTH_RCVD,
	SLOCUM_EVNT_USER_PARAM_PWR_ON_RCVD,
	SLOCUM_EVNT_USER_PARAM_PWR_OFF_RCVD,
	SLOCUM_EVNT_USER_PARAM_MIN_DEPTH_RCVD,
	SLOCUM_EVNT_DEPTH_RCVD,
	SLOCUM_EVNT_CLK_RCVD,
	SLOCUM_EVNT_MISSION_ID_RCVD,
	SLOCUM_EVNT_FILE_CREATE_ERR_RCVD,
	SLOCUM_EVNT_FILE_WRITE_S_ERR_RCVD,
	SLOCUM_EVNT_FINAL_DEPTH_AT_SURFACE_RCVD,
	SLOCUM_EVNT_FINAL_DEPTH_DIVING_RCVD,
	SLOCUM_EVNT_FINAL_DEPTH_CLIMBING_RCVD,
	SLOCUM_EVNT_FILE_CREATE_ERR,
	SLOCUM_EVNT_FILE_WRITE_ERR,
	SLOCUM_EVNT_FILE_CLOSE_ERR,
	SLOCUM_EVNT_FILE_OPENED,
	SLOCUM_EVNT_FILE_OPEN_ERR,
	SLOCUM_EVNT_FILE_DATA_WRITTEN,
	SLOCUM_EVNT_FILE_CLOSED,
	SLOCUM_EVNT_USER_CMD_POFF,
	SLOCUM_EVNT_USER_CMD_PON,
	SLOCUM_EVNT_DOS_OFF,
	SLOCUM_EVNT_DOS_ON
};

enum fsm_states{
	FSM_CHANGE_STATE_TO_S0=200,
	FSM_CHANGE_STATE_TO_S1,
	FSM_CHANGE_STATE_TO_S2,
	FSM_CHANGE_STATE_TO_S3,
	FSM_CHANGE_STATE_TO_S4,
	FSM_CHANGE_STATE_TO_S5,
	FSM_CHANGE_STATE_TO_S6,
	FSM_CHANGE_STATE_TO_S7
};

enum fsm_events{
	FSM_EVNT_ERR_SENSOR_NOT_RESPOND=300,
	FSM_EVNT_UVP6_NOT_STARTED,
	FSM_EVNT_UVP6_NOT_STOPPED,
	FSM_EVNT_UVP6_STOPPED,
	FSM_EVNT_READY_FOR_PRE_CONFIG,
	FSM_EVNT_PRE_CONFIG_FINISHED,
	FSM_EVNT_READY_FOR_LPM_DATA,
	FSM_EVNT_WAIT_FOR_AGG_DATA,
	FSM_EVNT_SURFACED,
	FSM_EVNT_CLIMB_TO_SURFACE,
	FSM_EVNT_SURFACE_TO_DIVE,
	FSM_EVNT_CLIMB_TO_DIVE,
	FSM_EVNT_DIVE_TO_CLIMB,
	FSM_EVNT_SYS_ERROR
};


#endif /* INC_EVENTS_H_ */
