/*
 * events.h
 *
 *  Created on: Mar 30, 2023
 *      Author: admin
 */

#ifndef INC_EVENTS_H_
#define INC_EVENTS_H_

enum {

	 SEAGLIDER_EVNT_START_RCVD=600,
	 SEAGLIDER_EVNT_STOP_RCVD,
	 SEAGLIDER_EVNT_TEST_RCVD,
	 SEAGLIDER_EVNT_SEND_TXT_FILE_RCVD,
	 SEAGLIDER_EVNT_CLOCK_RCVD,
	 SEAGLIDER_EVNT_WAKEUP_RCVD,
	 SEAGLIDER_EVNT_DEPTH_RCVD,
	 SEAGLIDER_EVNT_CLEAR_RCVD,
	 SEAGLIDER_EVNT_POFF_RCVD,
	 SEAGLIDER_EVNT_ERRORS_RCVD,
};
enum {
	 UVP6_EVNT_BOOTED=500,
	 UVP6_EVNT_LPM_DATA_RCVD,
	 UVP6_EVNT_BLK_DATA_RCVD,
	 UVP6_EVNT_ACQ_CONF_RCVD,
	 UVP6_EVNT_START_ACK_RCVD,
	 UVP6_EVNT_START_ERR_RCVD,
	 UVP6_EVNT_STOP_ACK_RCVD,
	 UVP6_EVNT_ERR_NO_RESPONSE,
	 UVP6_EVNT_ERR_BUSY,
	 UVP6_EVNT_STARTED_LOW_PROFILE,
	 UVP6_EVNT_STARTED_HIGH_PROFILE,
	 UVP6_EVNT_POWERED_OFF,
	 UVP6_EVNT_POWERED_ON,
	 UVP6_EVNT_LPM_DATA_BLOC_END_REACHED,
	 UVP6_EVNT_LPM_AGG_DATA_READY,
	 UVP6_EVNT_LPM_BUFFER_CLEARED,
	 UVP6_EVNT_LPM_AGG_NOTHING_TO_SEND,
	 UVP6_EVNT_DEPTH_LH_REACHED_FROM_TOP,
	 UVP6_EVNT_DEPTH_LH_REACHED_FROM_BOTTOM,
};

enum fsm_states{
	FSM_CHANGE_STATE_TO_INIT=200,
	FSM_CHANGE_STATE_TO_IDLE,
	FSM_CHANGE_STATE_TO_STARTING,
	FSM_CHANGE_STATE_TO_DIVE,
	FSM_CHANGE_STATE_TO_STOPPING

};

enum fsm_events{
	FSM_EVNT_SETTINGS_LOADED=300,
	FSM_EVNT_DEFAULT_SETTINGS_LOADED,
	FSM_EVNT_SENSOR_INITIALIZED,
	FSM_EVNT_SENSOR_INIT_ERROR,
	FSM_EVNT_CLOCK_UPDATED,
	FSM_EVNT_ERRORS_SENT,
	FSM_EVNT_DATA_SENT,
	FSM_EVNT_DATA_CANT_BE_SENT,
	FSM_EVNT_DS4_DATA_READY,
	FSM_EVNT_TS1_DATA_READY,
	FSM_EVNT_DS4_PROCESSED,
	FSM_EVNT_TS1_PROCESSED,
	FSM_EVNT_FILES_CREATED,
	FSM_EVNT_FILES_OPENED,
	FSM_EVNT_FILES_CLOSED,
	FSM_EVNT_POST_CONF_FINISHED,
	FSM_EVNT_PRE_CONF_FINISHED,
	FSM_EVNT_FILE_OPEN_ERR,
	FSM_EVNT_DBG1,
	FSM_EVNT_DBG2,
	FSM_EVNT_READY_FOR_LPM_DATA,
	FSM_EVNT_UVP6_NOT_STARTED,
	FSM_EVNT_UVP6_NOT_STOPPED,
	FSM_EVNT_UVP6_STOPPED,
	FSM_EVNT_UVP6_ERR,
	FSM_EVNT_FILE_DATA_WRITTEN,
	FSM_EVNT_FILE_WRITE_ERR

};


#endif /* INC_EVENTS_H_ */
